import Vue from 'vue';

//文件的绝对路径
const pathOfFileVue='src/components';//页面文件路径
const pathOfFileCss='src/css'//css文件路径
const pathOfFileJS='src/filters'//公共js文件路径
const pathOfFileImg='src/image'//图片文件路径


//接口路由后缀部分
//首页
const purchaseTaskListURL = 'purchase_date/batch_task_list';//采购期-获取采购期任务列表（首页）
const firstPageURL = 'Demand/firstPage';//首页统计
const sumDemandInfoURL = 'Demand/sumDemandInfo';//获取合单下需求单的信息
const sumDiffInfoURL = 'Demand/sumDiffInfo';//查看合单缺口统计
const ddGoodsRankListURL = 'misOrder/ddGoodsRankList';//首页-DD单品排行
const getSaleUserURL = 'misOrder/getSaleUser';//获取销售用户
const uploadAdminUserImgURL = 'AdminUser/uploadAdminUserImg';//权限管理-管理员列表-上传管理员头像
//采购模块
const getWaiteOrder = 'purchase_date/date_list';//采购期-获取采购期列表
const createDate='purchase_date/create_date';//采购期-创建采购期
const passDateList='purchase_date/pass_date_list'//采购期-获取过往采购期列表接口
const editDate='purchase_date/edit_date'//采购期-打开编辑采购期详情页
const doEditDate='purchase_date/do_edit_date';//采购期-确认提交编辑采购期
const channelsListURL='purchase_channels/channels_list';//采购渠道-采购渠道列表
const createChannelsURL='purchase_channels/create_channels';//采购渠道-创建采购渠道
const createMethodURL='purchase_method/create_method';//采购方式-创建采购方式
const methodListURL='purchase_method/method_list';//采购方式-获取采购方式列表
const editMethodURL='purchase_method/edit_method';//采购方式-打开编辑采购方式详情页
const doEditMethodURL='purchase_method/do_edit_method';//采购方式-确认提交编辑采购方式
const discountListURL='purchase_discount/discount_list';//采购折扣-获取当前采购折扣列表
const downloadDiscountDemoURL='purchase_discount/download_discount_demo';//采购折扣-下载品牌折扣模板
const downloadDiscountCurrentURL='purchase_discount/download_discount_current';//采购折扣-下载当前采购折扣表
const uploadDiscountURL='purchase_discount/upload_discount';//采购折扣-品牌折扣上传
const createCostURL='purchase_cost/create_cost';//采购成本系数-创建采购成本系数
const costListURL='purchase_cost/cost_list';//采购成本系数-采购成本系数列表
const editCostURL='purchase_cost/change_cost_status';//采购成本系数-改变采购成本系数状态
const demandListURL='purchase_demand/demand_list';//采购需求-获取采购需求列表
const demandDetailURL='purchase_demand/demand_detail';//采购需求-打开采购需求详情页
const changeGoodsURL='purchase_demand/change_goods_info';//采购需求-改变采购需求中商品的信息
const changeDemandStatusURL='purchase_demand/change_demand_status';//采购需求-确认提交采购需求审核
const downloadDemandListURL='purchase_demand/download_demand_list';//采购需求-下载采购需求单表
const recommendListURL='purchase_recommend/recommend_list';//优采推荐-获取采购需求列表
const recommendDetailURL='purchase_recommend/recommend_detail';//优采推荐-打开采购需求详情页
const downloadRecommendListURL='purchase_recommend/download_recommend_list';//优采推荐-下载采购需求单表
const uploadDataURL='purchase_data/upload_data';//采购期-检测上传采购数据条件
const doUploadDataURL='purchase_data/do_upload_data';//采购数据-采购数据实时上传
const dataListURL='purchase_data/data_list';//采购数据-获取采购数据列表
const batchListURL='purchase_batch/batch_list';//采购实采批次-获取采购批次列表
const batchDetailURL='purchase_batch/batch_detail ';//采购数据-获取采购批次详情
const downloadBatchListURL='purchase_batch/download_batch_list';//采购实采批次-下载采购批次单表
const diffListURL='purchase_diff/diff_list';//差异管理-获取采购批次列表
const diffDetailURL='purchase_diff/diff_detail';//差异管理-获取采购批次详情
const changeDiffStatusURL='purchase_diff/change_diff_status';//差异管理-改变批次状态（确认差异或拒绝）
const expireDiffListURL='purchase_diff/expire_diff_list';//差异管理-获取超时确认差异采购批次列表
const billingListURL='purchase_billing/billing_list';//erp开单-获取采购批次列表
const billingDetailURL='purchase_billing/billing_detail';//erp开单-获取采购批次详情
const changeBillingStatusURL='purchase_billing/change_billing_status';//erp开单-改变批次状态
const expireBillingListURL='purchase_billing/expire_billing_list';//erp开单-获取超时开单采购批次列表
const userListURL='purchase_user/user_list';//采购id-获取采购id列表 
const createUserURL='purchase_user/create_user';//采购id-创建采购id
const checkPurchaseDatePassURL='purchase_data/checkPurchaseDatePass';//采购数据-检查采购期是否过期
const addDiffRemarkURL='purchase_diff/add_diff_remark';//差异管理-增加商品备注
const dataManagementListURL='data_management/dataManagementList';//数据管理-获取采购数据列表
const dataGoodsListURL='data_management/dataGoodsList';//数据管理-获取商品数据列表
const editUserURL='purchase_user/edit_user';//采购id-打开编辑采购id页面
const doEditUserURL='purchase_user/do_edit_user';//采购id-确认提交编辑采购id页面
const downloadDiffListURL='purchase_diff/download_diff_list';//差异管理-下载采购批次单表
const downloadBillingListURL='purchase_billing/download_billing_list';//erp开单-下载采购批次单表
const channelMethodListURL='purchase_date/channel_method_list';//采购期-采购渠道和采购方式表
const uploadDiffDataURL='purchase_data/uploadDiffData';//采购数据-采购数据修正上传
const douploadDiffDataURL='purchase_data/doUploadDiffData';//采购数据-采购数据修正上传
const closePurchaseURL='purchase_date/closePurchase';//采购期-关闭采购期
const modifyDataListURL='purchase_data/modifyDataList';//数据修正列表接口
const purchaseListURL='purchase_demand/purchaseList';//采购模块-需求管理-获取列表数据
const uploadDemandURL='purchase_demand/uploadDemand';//采购模块-提报需求-获取页面数据
const purchaseOutListURL='purchase_demand/purchaseOutList';//需求管理-过往需求-获取过往需求列表
const doUploadDemandURL='purchase_demand/doUploadDemand';//采购模块-提报需求-商品上传
const waitAllotDemandURL='purchase_demand/waitAllotDemand';//采购模块-获取待分配需求列表
const alreadyAllotDemandURL='purchase_demand/alreadyAllotDemand';//采购模块-已分配需求列表
const demandAttachURL='purchase_demand/demandAttach';//采购模块-需求管理-获取符合需求的采购期列表
const doDemandAttachURL='purchase_demand/doDemandAttach';//采购模块-需求管理-提交需求挂期
const demandAllotURL='purchase_demand/demandAllot';//采购模块-需求管理-待分配-获取采购期需求汇总详情
const purchaseDemandAllotURL='purchase_demand/purchaseDemandAllot';//采购模块-需求管理-待分配-获取某一采购期需求详情
const editDemandAllotURL='purchase_demand/editDemandAllot';//采购模块-需求管理-待分配-打开编辑采购期可采数
const doEditDemandAllotURL='purchase_demand/doEditDemandAllot';//采购模块-需求管理-待分配-提交编辑采购期可采数
const demandDetailTURL='purchase_demand/demandDetail';//采购模块-需求管理-已分配-获取采购期需求汇总详情
const demandAlreadyDetailURL='purchase_demand/demandAlreadyDetail';//采购模块-需求管理-已分配-获取采购期需求汇总详情
const purchaseDemandAlreadyURL='purchase_demand/purchaseDemandAlready';//采购模块-需求管理-已分配-获取某一采购期需求详情
const doDemandAllotURL='purchase_demand/doDemandAllot';//采购模块-需求管理-待分配-提交确认的需求分配方案
const departSortGoodsURL='purchase_date/depart_sort_goods';//采购期列表-根据采购单号按部门进行分货
const predictDemandListURL='purchase_predict/predictDemandList';//采购模块-预采需求管理-预采需求列表
const downloadPredictDemandtURL='purchase_predict/downloadPredictDemand';//采购模块-预采需求管理-下载预采需求列表
const uploadPredictRealURL='purchase_predict/uploadPredictReal';//采购模块-预采需求管理-上传预采批次
const doUploadPredictRealURL='purchase_predict/doUploadPredictReal';//采购模块-预采需求管理-确认上传预采批次
const predictDetailURL='purchase_predict/predictDetail';//采购模块-预采需求管理-获取预采需求单详情
const vipDiscountListURL='discount/vip_discount_list';//采购模块-采购折扣管理-获取当前采购vip折扣列表
const doBatchSettingPostURL='purchase_batch/doBatchSettingPost';//采购模块-采购数据管理-批次到货设置运费
const supplierListURL='supplier/supplierList';//采购模块-供应商管理-供应商列表
const addSupplierURL='supplier/addSupplier';//采购模块-供应商管理-添加供应商
const editChannelURL='channel/editChannel';//采购模块-优采推荐管理-采购方式-打开编辑采购渠道详情页
const doEditChannelURL='channel/doEditChannel';//采购模块-采购方式-确认提交编辑采购渠道
const addBrandDiscountURL='Discount/addBrandDiscount';//采购模块-优采推荐管理-采购折扣-新增品牌折扣
const doAddBrandDiscountURL='Discount/doAddBrandDiscount';//采购模块-优采推荐管理-采购折扣-提交新增品牌折扣
const downLoadWaitAllotGoodsInfoURL='Demand/downLoadWaitAllotGoodsInfo';//采购模块-需求管理-下载需求单指定采购期下的待分配数据
const uploadWaitAllotGoodsInfoURL='Demand/uploadWaitAllotGoodsInfo';//采购模块-需求管理-上传需求单指定采购期下的分配数据
const batchAddBrandDiscountURL='Discount/batchAddBrandDiscount';//采购模块-优采规则管理-品牌采购折扣批量新增
const batchAuditListURL='Batch/batchAuditList';//采购模块-采购数据管理-批次审核
const purchaseDemandListURL='Demand/purchaseDemandList';//采购需求列表
const sumPurchaseDemandURL='Demand/sumPurchaseDemand';//合并需求单
const demandPurchaseTaskListURL='Demand/purchaseTaskList';//采购任务列表
const downLoadSumDemandGoodsInfoURL='Demand/downLoadSumDemandGoodsInfo';//下载汇总单的待分配数据
const purchaseTaskDetailURL='Demand/purchaseTaskDetail';//采购任务详情
const uploadBatchDataURL='Data/uploadBatchData';// 采购数据上传（新）
const uploadSumDemandGoodsInfoURL='Demand/uploadSumDemandGoodsInfo';//上传汇总单的分配数据
const BatchUploadBatchDataURL='Batch/uploadBatchData';//
const doUploadBatchDataURL='Batch/doUploadBatchData';//
const purchaseDemandDetailURL='Demand/purchaseDemandDetail';//采购需求详情
const addSumDemandURL='Demand/addSumDemand';//打开追加合单页面
const doAddSumDemandURL='Demand/doAddSumDemand';//提交追加合单
const downLoadSdgInfoNoSortURL='Demand/downLoadSdgInfoNoSort';//下载汇总单的待分配数据（无序）
const splitSumDemandURL='Demand/splitSumDemand';//拆分合单需求单
const getCardConsumeListURL='Finance/getCardConsumeList';//采购模块-采购任务管理-采购金额列表
const addCardConsumeURL='Finance/addCardConsume';//采购模块-采购任务管理-打开维护采购金额页面
const doAddCardConsumeURL='Finance/doAddCardConsume';//采购模块-采购任务管理-维护采购金额
const teamListURL='Channel/teamList';//获取团队列表
const addTeamURL='Channel/addTeam';//新增团队
const editTeamURL='Channel/editTeam';//编辑团队

//销售模块
const managerURL='demand/manager';//采购需求管理
const demGoodsUpURL='demand/demGoodsUp';//采购需求列表-上传商品明细
const getPageDataURL='demand/getPageData';//采购需求管理-客户需求汇总明细数据
const getCompletePurListURL='demand/getCompletePurList';//采购需求管理-过往需求列表
const getGoodsAllotListURL='goodsAllot/batchListPredict';//商品分配管理-预测分配接口
const getGoodsActAllotListURL='goodsAllot/batchListReal';//商品分配管理-实采商品分配-列表数据获取
const getGoodsAllotURL='goodsAllot/getGoodsAllotPredict';//商品分配管理-商品预测分配详情页数据
const goodsRealAllotURL='goodsAllot/getGoodsAllotReal';//商品分配管理-实时分配预测
const goodsRtMovePercentURL='goodSale/goodsRtMovePercent';//销售数据管理-商品实时动销率
const getGoodsAllotTwoURL='goodsAllot/getGoodsAllot';//销售数据管理-商品实时动销率
//const getWaiteOrderURL='order/getWaiteOrder';//订单管理-查看代发货订单+订单管理-超时发货订单+订单发货管理-待发货订单+订单发货管理-超时未发货
//const getWaitCusOrderURL='order/getWaitCusOrder';//订单管理-查看待清关订单+超时清关订单+清关管理-待清关订单
const sellWaitOrderURL='order/sellWaitOrder';//订单管理-获取待发货订单(销售)
const sellOutOrderURL='order/sellOutOrder';//订单管理-获取超时发货订单(销售)
const sellCusOrderURL='order/sellCusOrder';//订单管理-获取待清关订单(销售)
const sellOutCusOrderURL='order/sellOutCusOrder';//订单管理-获取超时清关订单(销售)
const getGoodsAllotRealURL='goodsAllot/getGoodsAllotReal';//采购期-获取采购期批次任务列表(预测)
const queryDemDetailURL='demand/queryDemDetail';//需求管理-需求列表-根据需求单号获取商品需求数据
const getRealPurListURL='goodsAllot/getRealPurList';//商品分配管理-商品实际分配（按部门）- 获取批次单列表
const getRealGoodsInfoURL='goodsAllot/getRealGoodsInfo';//商品分配管理-商品实际分配（按部门）- 根据批次单号获取对应商品信息
const updateRealAllotNumURL='goodsAllot/updateRealAllotNum';//商品分配管理-商品实际分配（按部门）- 以批次单号为基准对商品数量进行分配
const getPurOrderListURL='goodsAllot/getPurOrderList';//商品分配管理-商品分配-获取采购单列表(不论是否挂了需求单)
const getPurDemOrdListURL='goodsAllot/getPurDemOrdList';//商品分配管理-商品分配-采购单列表-点击采购单号进入对应需求单号
const getPurDemOrdInfoURL='goodsAllot/getPurDemOrdInfo';//商品分配管理-商品分配-采购单列表-需求单列表-点击需求单号进入需求单对应的商品信息
const getNeedGoodsListURL='demand/getNeedGoodsList';//销售模块-需求管理-需求商品报价-获取需求列表  
const demandAllotListURL='goodsAllot/demandAllotList';//商品分配管理-需求单列表
const demandPurchaseListURL='goodsAllot/demandPurchaseList';//商品分配管理-需求采购列表
const demandPurchaseDetailURL='goodsAllot/demandPurchaseDetail';//商品分配管理-需求采购期详情
const newDemPageURL='demand/newDemPage';//需求管理-需求列表-新增需求页面
const updateSaleRateURL='demand/updateSaleRate';//需求列表-需求详情-修改销售折扣
const getChannelByMethodURL='purchase_data/getChannelByMethod';//采购模块-采购数据管理-实时数据上传-通过方式获取渠道(接口已废弃)
const depHandleGoodsURL='purchase_date/dep_handle_goods';//采购期列表-根据采购单号以批次单为主按部门进行分货-手动修改分货数量
const userSortGoodsURL='purchase_date/user_sort_goods';//各部门根据商品部分好的数据对相应的销售客户进行分货
const usrHandleGoodsURL='purchase_date/usr_handle_goods';//各部门根据商品部分好的数据对相应的销售客户进行分货-手动修改分货数量
const getDemandDetialURL='purchase_demand/getDemandDetial';//采购模块-需求管理管理-查看需求详情
const purRealListURL='purchase_date/pur_real_list';//采购单-批次单-分货列表
const demandAllotDetailURL='goodsAllot/demandAllotDetail';//销售模块-商品分配管理-需求单汇总信息
const demandPassageListURL='goodsPassage/demandPassageList';//销售模块-在途商品-在途商品列表
const passageRealPurchaseListURL='goodsPassage/passageRealPurchaseList';//销售模块-在途商品-在途需求单对应采购期的批次列表
const passageRealPurchaseDetailURL='goodsPassage/passageRealPurchaseDetail';//销售模块-在途商品-在途需求单对应采购期的批次详情
const saleAccountListURL='sale_user/saleAccountList';//销售模块-销售客户账号管理-销售客户账号列表
const addSaleAccountURL='sale_user/addSaleAccount';//销售模块-销售客户账号管理-新增销售客户账号
const doAddSaleAccountURL='sale_user/doAddSaleAccount';//销售模块-销售客户管理-确认新增销售客户账号
const editSaleAccountURL='sale_user/editSaleAccount';//销售模块-销售客户账号管理-编辑销售客户账号
const doEditSaleAccounttURL='sale_user/doEditSaleAccount';//销售模块-销售客户管理-确认编辑销售客户账号
const getMisOrderListURL='misOrder/getMisOrderList';//MIS订单管理-获取总订单列表
const getMisOrderDetailURL='misOrder/getMisOrderDetail';//MIS订单管理-获取总订单详情
const refundRulesListURL='sale_user/refundRulesList';//销售模块-回款规则管理-销售客户回款规则列表
const addRefundRulesURL='sale_user/addRefundRules';//销售模块-回款规则管理-新增销售客户回款规则
const doAddRefundRulesURL='sale_user/doAddRefundRules';//销售模块-回款规则管理-新增销售客户回款规则
const editRefundRulesURL='sale_user/editRefundRules';//销售模块-回款规则管理-编辑销售客户回款规则
const doEditRefundRulesURL='sale_user/doEditRefundRules';//销售模块-回款规则管理-确认编辑销售客户回款规则
const misSubOrderListURL='mis_order/misSubOrderList';//销售模块-MIS订单管理管理-获取YD订单列表
const misCanDeliverGoodsURL='mis_order/misCanDeliverGoods';//销售模块-MIS订单管理管理-获取YD订单下可发货的商品
const comfirmDeliverGoodsURL='mis_order/comfirmDeliverGoods';//销售模块-MIS订单管理管理-生成发货单
const getSubListURL='misOrder/getSubList';//MIS订单管理-获取子订单列表
const getSubDetailURL='misOrder/getSubDetail';//子订单列表-获取子订单详情
const getSpotListURL='misOrder/getSpotList';//MIS订单管理-现货单列表
const getSpotDetailURL='misOrder/getSpotDetail';//现货单列表-获取现货单详情
const importOrderPageURL='misOrder/importOrderPage';//MIS订单管理-导入总单页面
const importOrderURL='misOrder/importOrder';//MIS订单管理-订单商品报价
const ordGoodsOfferURL='misOrder/ordGoodsOffer';//MIS订单管理-订单商品报价
const orderAffiliateURL='misOrder/orderAffiliate';//MIS订单管理-总单挂靠(加入交付时间和销售账户)
const cancelSpotOrdURL='misOrder/cancelSpotOrd';//取消现货单并将其推送至
const erpOrderPushURL='misOrder/erpOrderPush';//现货单推送到
const exportSubOrdURL='misOrder/exportSubOrd';//现货单详情-导出订单
const importSubOrdURL='misOrder/importSubOrd';//子单-导入BD单
const listSaleAccountURL='misOrder/listSaleAccount';//获取销售客户下的销售账号
const orderSubmenuURL='misOrder/orderSubmenu';//MIS订单管理-总单根据交付时间和销售账户进行分单
const subOrdSubmenuURL='misOrder/subOrdSubmenu';//子订单列表-分单操作（根据库存分为现货和采购单）
const modSaleDiscountURL='misOrder/modSaleDiscount';//总单报价-修改销售折扣
const demandGoodsMarkURL='demand/demandGoodsMark';//需求单详情-商品预采标记
const sellDeliverOrderListURL='deliver/sellDeliverOrderList';//销售模块-MIS订单管理管理-发货单列表
const downloadSellDeliverOrderURL='deliver/downloadSellDeliverOrder';//销售模块-MIS订单管理管理-发货单列表-下载发货单
const doUploadSellDeliverOrderURL='deliver/doUploadSellDeliverOrder';//销售模块-MIS订单管理管理-发货单列表-上传理货报告
const misOrderExportURL='misOrder/misOrderExport';//MIS订单管理-总单详情-导出总单信息
const finishOfferURL='misOrder/finishOffer';//商品报价页面-完成报价
const batchModSaleDiscountURL='misOrder/batchModSaleDiscount';//总单报价-根据选定自采毛利率批量修改销售折扣
const modifyWaitLockNumURL='misOrder/modifyWaitLockNum';//子单详情-修改锁库数量
const modifyRemarkURL='misOrder/modifyRemark';//子单详情-修改子单备注
const editArriveStoreTimeURL='Demand/editArriveStoreTime';//销售模块-MIS订单管理-需求单列表-编辑期望到仓日
const generalDepartSortDataURL='purchase_date/generalDepartSortData';//采购期列表-商品部对部门分货-生成分货数据
const getSortDataURL='purchase_date/getSortData';//销售模块-批次分货列表-查看分货数据
const generalUserSortDataURL='purchase_date/generalUserSortData';//部门分货页面-生成对销售用户的分货数据
const getUserSortDataURL='purchase_date/getUserSortData';//查询订单分货数据
const userHandleGoodsURL='purchase_date/user_handle_goods';//批次单列表-商品部对用户分货-手动修改分货数量
const modSaleDiscountBySpecURL='misOrder/modSaleDiscountBySpec';//总单报价-根据选定的sku批量修改对应销售折扣
const finishAdvanceURL='misOrder/finishAdvance';//商品报价页面-完成预判
const makePerDepartSortDataURL='purchase_date/makePerDepartSortData';//预采批次-生成部门分货数据
const finishAffiliatedURL='misOrder/finishAffiliated';//总单详情页面-完成挂靠
const batchAffiliateURL='misOrder/batchAffiliate';//总单详情-订单批量挂靠
const getOrderNewGoodsURL='misOrder/getOrderNewGoods';//总单详情-查看总单新品
const queryNewGoodsDataURL='misOrder/queryNewGoodsData';//总单新品-查询单条新品数据
const modifyNewGoodsDataURL='misOrder/modifyNewGoodsData';//总单新品信息-修改商品数据
const addNewGoodsDataURL='misOrder/addNewGoodsData';//总单新品-单条商品新增
const batchAddNewGoodsURL='misOrder/batchAddNewGoods';//总单新品-商品批量新增
const replenishGoodsIntoOrderURL='misOrder/replenishGoodsIntoOrder';//总单新品-补充新品到对应总单中
const addSpecPageURL='misOrder/addSpecPage';//总单新品-新增规格
const searchGoodsNameURL='misOrder/searchGoodsName';//总单新品-新增规格-品名搜索
const exportAdvanceURL='misOrder/exportAdvance';//预判数据导出
const markGoodsPostponeURL='Demand/markGoodsPostpone';//销售模块-需求管理-需求单详情-标记延期商品
const getMisOrderSplitURL='misOrder/getMisOrderSplit';//查看总单下的子单
const submitDDataURL='misOrder/submitDData';//DD数据提交
const modifyDDSubDataURL='misOrder/modifyDDSubData';//修改DD子单数据 
const batchOrderListURL='purchase_date/batchOrderList';//批次单列表
const generalSortDataURL='purchase_date/generalSortData';//根据总单号生成分货数据
const sumSortDataListURL='purchase_date/sumSortDataList';//查看合单号对应的总分货数据
const batchOrdSortDataURL='purchase_date/getBatchOrdSortData';//查看批次单分货数据
const handleSortNumURL='purchase_date/handleSortNum';//手动调整分配数据
const makeBatchOrdSortDataURL='purchase_date/makeBatchOrdSortData';//生成批次单分货数据
const exportOrdNewURL='misOrder/exportOrdNew';//导出总单新品
const importOrdNewURL='misOrder/importOrdNew';//批量更新总单新品
const exportOfferURL='misOrder/exportOffer';//商品报价-导出商品信息
const importOfferURL='misOrder/importOffer';//单商品报价-导入报价销售折扣
const downLoadDailyInfoURL='Statistics/downLoadDailyInfo';//日报
const getGoodsNewPriceURL='misOrder/getGoodsNewPrice';//商品价格变动详情
const modifyNewPriceURL='misOrder/modifyNewPrice';//修改价格
const submitNewPriceURL='misOrder/submitNewPrice';//商品新价格页面-提交价格
const demandDemandListURL='demand/demandList';//销售模块-需求管理-获取列表数据

//物流模块
const goodsCheckListURL='logistics/goodsCheckList';//商品清点-待清点采购单+超时未入库+入库管理-待入库采购单
const goodsCheckOutListURL='logistics/goodsCheckOutList';//商品清点-获取超时未清点采购单
const goodsStockOutListURL='logistics/goodsStockOutList';//
const goodsStockListURL='logistics/goodsStockList';
const allotGoodsURL='logistics/allotGoods';//商品清点-待清点详情页数据
const allotStockGoodsURL='logistics/allotStockGoods';//入库管理-待入库采购单清点页面
const allotGoodsNumURL='logistics/allotGoodsNum';//商品清点-单个改变商品状态
const sureAllotURL='logistics/sureAllot';//商品清点-确认清点
const downloadAllotGoodsURL='logistics/downloadAllotGoods';//商品清点-下载表格+入库管理-下载表格
const getCusTransitOrderURL='order/getCusTransitOrder';//商品清点-待入库采购单+待转关+超时未转关
const inputStorageURL='logistics/inputStorage';//入库管理-确认入库
const LigWaitOrderURL='order/ligWaitOrder'//订单管理-获取待发货订单(物流)
const ligOutOrderURL='order/ligOutOrder'//订单管理-获取超时发货订单(物流)
const ligCusOrderURL='order/ligCusOrder'//订单管理-获取待清关订单(物流)
const ligOutCusOrderURL='order/ligOutCusOrder'//订单管理-获取超时清关订单(物流)
const uploadWaitCusOrdURL='order/uploadWaitCusOrd';//订单管理-待清关订单-上传清关订单
const uploadCusTransitOrdURL='order/uploadCusTransitOrd';//清关管理-待转关订单-上传已转关订单
const uploadAllotDataURL='logistics/uploadAllotData';//物流模块-商品清点-清点数据批量上传
const getOutCusTransitOrderURL='order/getOutCusTransitOrder';//清关管理-超时未转关
const upDeliverOrdURL='order/upDeliverOrd';//待转关订单-上传发货订单
const distributionOrderListURL='mis_order/distributionOrderList';//物流模块-MIS订单管理管理-配货单列表
const distributionOrderDetailURL='mis_order/distributionOrderDetail';//物流模块-MIS订单管理管理-配货单详情
const downloadDistributionOrderURL='mis_order/downloadDistributionOrder';//物流模块-MIS订单管理管理-下载配货单
const doUploadDistributionOrderURL='mis_order/doUploadDistributionOrder';//物流模块-MIS订单管理管理-确认上传配货单
const sellReturnOrderListURL='deliver/sellReturnOrderList';//物流模块-MIS订单管理管理-退货单列表
const sellReturnOrderDetailURL='deliver/sellReturnOrderDetail';//物流模块-MIS订单管理管理-退货单详情
const downloadSellReturnGoodsURL='deliver/downloadSellReturnGoods';//物流模块-MIS订单管理管理-下载退货单数据
const doUploadSellReturnGoodsURL='deliver/doUploadSellReturnGoods';//物流模块-MIS订单管理管理-上传退货清点数据
const stopDepartSortDataURL='purchase_date/stopDepartSortData';//批次单列表-部门分货数据-停用部门分货数据
const addSpecDataURL='misOrder/addSpecData';//总单新品-新增规格-提交
const submitSubOrdURL='misOrder/submitSubOrd';//子订单详情-DD单数据提交
const importDDSubOrdURL='misOrder/importDDSubOrd';//总单详情-导入DD子单数据
const downLoadTodayPurTaskURL='Demand/downLoadTodayPurTask';//下载当日采购任务
//权限接口
const getPermissionURL='permission/getPermission';
const addPermissionURL='permission/addPermission';//权限管理-添加权限
const permissiomListURL='permission/permissiomList';//权限管理-权限列表
const addRoleURL='permission/addRole';//权限管理-添加角色
const roleListURL='Role/roleList';//权限管理-获取角色列表
const editRoleURL='permission/editRole';//权限管理-打开编辑角色页面
const addAdminUserURL='permission/addAdminUser';//权限管理-添加管理员
const adminUserListURL='AdminUser/adminUserList';//权限管理-获取管理员列表
const eidtAdminUserURL='permission/eidtAdminUser';//权限管理-改变管理员角色
const getAdminUserInfoURL='AdminUser/getAdminUserInfo';//权限管理-管理员列表-获取管理员信息
//查看汇总详情
const recommendTotalDetailURL='purchase_recommend/recommend_total_detail';//优采推荐-打开采购需求汇总详情页
const downloadRecommendTotalListURL='purchase_recommend/download_recommend_total_list';//优采推荐-下载采购需求总表
const demandTotalDetailURL='purchase_demand/demand_total_detail';//采购需求-打开采购需求汇总详情页
const downloadDemandTotalListURL='purchase_demand/download_demand_total_list';//采购需求-下载采购需求总表
const dataTotalDetailURL='purchase_data/data_total_detail';//采购数据-获取采购数据汇总信息
const downloadDataTotalListURL='purchase_data/download_data_total_list';//采购数据-下载采购数据总表
const batchTotalDetailURL='purchase_batch/batch_total_detail';//采购数据-获取采购批次汇总详情
const downloadBatchTotalListURL='purchase_batch/download_batch_total_list';//采购实采批次-下载采购批次总表
const diffTotalDetailURL='purchase_diff/diff_total_detail';//差异管理-获取采购批次汇总详情
const downloadDiffTotalListURL='purchase_diff/download_diff_total_list';//差异管理-下载采购批次总表
const billingTotalDetailURL='purchase_billing/billing_total_detail';//erp开单-获取采购批次汇总详情
const downloadBillingTotalListURL='purchase_billing/download_billing_total_list';//erp开单-下载采购批次总表
//任务模块
const taskListURL='purchase_task/task_list';//任务模块-任务列表
const addTaskDetailURL='purchase_task/add_task_detail';//任务模块-新增任务详情
const addTaskURL='purchase_task/add_task';//任务模块-新增任务详情
const userOfRoleURL='admin_user_role/userOfRole';//采购任务-通过角色id获取管理员列表
const getPurchaseTaskURL='purchase_date/getPurchaseTask';//定时任务-获取需要提醒的采购期任务信息
const changeTaskStatusURL='purchase_task/changeTaskStatus';//定时任务-弹出提示点击是调用接口
const batchSettingURL='purchase_batch/batchSetting';//采购实采批次-批次到货设置
const doBatchSettingURL='purchase_batch/doBatchSetting';//采购实采批次-批次到货设置修改接口
const taskModelListURL='task/taskModelList';//获取任务模板表
const checkTaskModelURL='purchase_task/check_task_model';//任务模块-检测任务模板
const editTaskURL='purchase_task/editTask';//任务模块-编辑任务
const doEditTaskURL='purchase_task/doEditTask';//任务模块-提交编辑任务
//商品模块
const goodsListURL='goods/goodsList';//商品模块-商品列表
const changeSaleStatusURL='goods/changeSaleStatus';//商品模块-改变商品上下架状态
const doAddGoodsURL='goods/doAddGoods';//商品模块-新增单个商品
const addGoodsURL='goods/addGoods';//商品模块-打开新增商品页面
const uploadGoodsImgURL='goods/uploadGoodsImg';//商品模块-上传商品主图
const uploadAddGoodsURL='goods/uploadAddGoods';//商品模块-批量新增商品
const editGoodsURL='goods/editGoods';//商品模块-打开商品编辑页面
const doEditGoodsURL='goods/doEditGoods';//商品模块-提交编辑商品
const saleUserListURL='goods/saleUserList';//商品模块-销售用户列表
const userGoodsListURL='goods/UserGoodsList';//商品模块-销售用户商品列表
const upSaleGoodsURL='goods/upSaleGoods';//商品模块-上传销售用户商品数据
const modSaleRateURL='goods/modSaleRate';//商品模块-单个修改销售折扣
const batchSaleDisURL='goods/batchSaleDis';//商品模块-批量修改销售折扣
const addCustomerURL='purchase_customer/addCustomer';//商品模块-商品管理-新增销售客户
const doAddCustomerURL='purchase_customer/doAddCustomer';//商品模块-商品管理-确认新增销售客户
const goodsSpecListURL='goods/goodsSpecList';//商品模块查看商品规格详情
const doAddGoodsSpecURL='goods/doAddGoodsSpec';//新增商品规格
const editGoodsSpecURL='goods/editGoodsSpec';//打开商品规格编辑页面
const doEditGoodsSpecURL='goods/doEditGoodsSpec';//提交编辑商品规格
const editCustomerURL='purchase_customer/editCustomer';//编辑销售客户
const doEditCustomerURL='purchase_customer/doEditCustomer';//确认编辑客户
const getErpGoodsListURL='goods/getErpGoodsList';//获取erp商品列表
const addGoodsCodeURL='goods/addGoodsCode';//打开新增商品规格页面
const doAddGoodsCodeURL='goods/doAddGoodsCode';//提交新增商品编码
const editGoodsCodeURL='goods/editGoodsCode';//打开商品编码编辑页面
const goodsLabelListURL='Goods/goodsLabelList';//商品标签列表
const doAddGoodsLabelURL='Goods/doAddGoodsLabel';//新增商品标签
const editGoodsLabelURL='Goods/editGoodsLabel';//提交编辑商品标签页面
const doEditGoodsLabelURL='Goods/doEditGoodsLabel';//提交编辑商品标签
const doEditGoodsCodeURL='goods/doEditGoodsCode';//提交编辑商品编码
const addGoodsSpecURL='goods/addGoodsSpec';//打开新增商品规格页面
const standbyGoodsListURL='Goods/standbyGoodsList';//商品模块-商品管理-常备商品列表录
const standbyGoodsInfoURL='Goods/standbyGoodsInfo';//商品模块-商品管理-常备商品详情
const doEditStandbyGoodsURL='Goods/doEditStandbyGoods';//商品模块-商品管理-编辑常备商品
const uploadStandbyGoodsDataURL='Goods/uploadStandbyGoodsData';//商品模块-商品管理-上传常备商品
const downLoadStandbyGoodsInfoURL='Goods/downLoadStandbyGoodsInfo';//商品模块-商品管理-下载常备商品
const addStandbyGoodsURL='goods/addStandbyGoods';//单个新增常备商品
const uploadStandbyGoodsURL='goods/uploadStandbyGoods';//批量新增常备商品
const offerListURL='goods/offerList';//报价列表
const getOfferDetailURL='goods/getOfferDetail';//客户订单报价--获取报价详情
const offerSkuUploadURL='goods/offerSkuUpload';//客户订单报价--上传需要报价的
const modifySkuDiscountURL='goods/modifySkuDiscount';//客户订单报价--单个修改销售折扣
const exportSkuOfferURL='goods/exportSkuOffer';//客户订单报价--导出数据
const importSkuOfferURL='goods/importSkuOffer';//客户订单报价--导入报价
const goodsDetailURL='goods/goodsDetail';//商品模块-平台商品列表-商品详情
const ltGoodsListURL='Goods/ltGoodsList';//商品模块-乐天商品列表
const ltGoodsSpecPriceInfoURL='Goods/ltGoodsSpecPriceInfo';//商品模块-乐天商品美金原价信息
const wholesaleListURL='goods/wholesaleList';//大批发报价列表接口
const getWholesaleDetailURL='goods/getWholesaleDetail';//大批发报价单详情接口
const importWholesaleSkuURL='goods/importWholesaleSku';//大批发报价报价--上传需要报价的SKU
const exportWholesaleOfferURL='goods/exportWholesaleOffer';//大批发报价详情-数据导出
const getWholeDetailURL='goods/getWholeDetail';//大批发报价报价--报价详情
const wholesaleExportURL='goods/wholesaleExport';//大批发报价详情-数据导出-新版
const modifyWholeDataURL='goods/modifyWholeData';//大批发报价-详情-修改运输方式和参考折扣
const batchModifyWholeDataURL='goods/batchModifyWholeData';//大批发报价-详情-批量修改运输方式和参考折扣

//公告模块
const addNoticeURL='notice/addNotice';//公告模块-新增公告
const noticeListURL='Notice/noticeList';//公告模块-公告列表
//报价器
const queryNeedGoodsInfoURL='demand/queryNeedGoodsInfo';//销售模块-需求管理-需求商品报价-获取需求列表-点击报价计算-获取需求单下面的商品信息
const addMarginRateURL='demand/addMarginRate';//点击报价计算-报价计算页面-新增自采毛利率
const modifyPricingRateURL='demand/modifyPricingRate';//点击报价计算-报价计算页面-单个修改销售折扣
const batchModPricRateURL='demand/batchModPricRate';//点击报价计算-报价计算页面-批量修改销售折扣
const getChargeListURL='demand/getChargeList';//销售模块-需求管理-获取费用列表
const addChargeURL='demand/addCharge';//销售模块-需求管理-获取费用列表-新增费用项
const modifyChargeURL='demand/modifyCharge';//销售模块-需求管理-获取费用列表-修改费用项
//订单列表
const getOrderListURL='order/getOrderList';//订单管理-获取订单列表
const orderDetailURL='order/orderDetail';//订单管理-订单详情
//财务模块
const getFundChannelListURL='fund_channel/getFundChannelList';//财务模块-财务渠道管理-资金渠道列表
const doAddFundChannelURL='fund_channel/doAddFundChannel';//财务模块-财务渠道管理-确认新增资金渠道
const addFundChannelURL='fund_channel/addFundChannel';//财务模块-财务渠道管理-打开新增资金渠道
const editFundChannelURL='fund_channel/editFundChannel';//财务模块-财务渠道管理-编辑资金渠道
const doEditFundChannelURL='fund_channel/doEditFundChannel';//财务模块-财务渠道管理-确认编辑资金渠道
const rongFundListURL='fund/rongFundList';//财务模块-财务渠道管理-可融资金列表
const editRongFundURL='fund/editRongFund';//财务模块-财务渠道管理-编辑可融资金
const doEditRongFundURL='fund/doEditRongFund';//财务模块-财务渠道管理-确认编辑可融资金
const discretionaryFundListURL='fund/discretionaryFundList';//财务模块-财务渠道管理-自有可支配资金列表
const editDiscretionaryFundURL='fund/editDiscretionaryFund';//财务模块-财务渠道管理-编辑自有可支配资金
const doEditDiscretionaryFundURL='fund/doEditDiscretionaryFund';//财务模块-财务渠道管理-确认编辑自有可支配资金
const waitRefundListURL='fund/waitRefundList';//财务模块-需求资金管理-需求资金列表
const demandFundListURL='fund/demandFundList';//财务模块-需求资金管理-需求资金列表
const financeDeliverOrderListURL='mis_order/financeDeliverOrderList';//财务模块-MIS订单管理管理-发货单列表
const financeChangeOrderStatusURL='mis_order/financeChangeOrderStatus';//财务模块-MIS订单管理管理-确认收款
const watiPricingBatchListURL='Finance/watiPricingBatchList';//财务模块-核价管理-获取待核价批次列表
const watiPricingBatchDetailURL='finance/watiPricingBatchDetail';//财务模块-核价管理-获取待核价批次详情
const downloadPricingBatchDetailURL='finance/downloadPricingBatchDetail';//财务模块-核价管理-下载待核价批次数据
const doUploadPricingBatchURL='finance/doUploadPricingBatch';//财务模块-核价管理-上传核价批次数据
const changePriceStatusURL='finance/change_price_status';//财务模块-核价管理-改变批次状态（确认核价）
const fundListDetailURL='fund/fundListDetail';//财务模块-需求资金管理-需求资金详情列表
const doPricingBatchURL='finance/doPricingBatch';//财务模块-核价管理-提交批次核价
const demandGoodsFundListURL='fund/demandGoodsFundList';//财务模块-需求资金管理-需求单剩余需求资金列表
const waitRefundDemandListURL='Fund/waitRefundDemandList';//财务模块-待回款资金管理-待回款资金需求单列表
const waitRefundDemandDetailURL='Fund/waitRefundDemandDetail';//财务模块-待回款资金管理-待回款资金需求详情
const exchangeRateListURL='Finance/exchangeRateList';//财务模块-获取汇率列表
const uploadExchangeRateURL='Finance/uploadExchangeRate';//财务模块-上传汇率
const getProfitFormulaListURL='Finance/getProfitFormulaList';//财务模块-毛利数据管理-获取毛利公式列表
const getDiscountCatListURL='Finance/getDiscountCatList';//财务模块-毛利数据管理-获取折扣类型列表
const doAddProfitFormulaURL='Finance/doAddProfitFormula';//财务模块-毛利数据管理-新增毛利公式
const profitListURL='Finance/profitList';//财务模块-毛利数据管理-新增毛利公式
const discountTypeListFinanceURL='Finance/discountTypeList';//点击生成毛利数据时获取信息
const generateProfitURL='Finance/generateProfit';//财务模块-毛利数据管理-生成毛利数据
const profitDetailURL='Finance/profitDetail';//财务模块-毛利数据管理-毛利数据详情
const downLoadProfitInfoURL='Finance/downLoadProfitInfo';//财务模块-毛利数据管理-下载毛利数据
const deleteProfitInfoURL='Finance/deleteProfitInfo';//财务模块-毛利数据管理-停用毛利数据
const doAddDiscountCatURL='Finance/doAddDiscountCat';//财务模块-毛利数据管理-获取折扣类型种类列表
const getCatFormulaListURL='Finance/getCatFormulaList';//财务模块-毛利管理-获取折扣种类公式列表
const addCatFormulaURL='Finance/addCatFormula';//财务模块-毛利数据管理-打开新增类型公式页面
const doAddCatFormulaURL='Finance/doAddCatFormula';//财务模块-毛利数据管理-新增种类公式


//数据汇总模块
const misDemandListURL='demand/misOrderStatisticsList';//数据统计模块-订单管理-总单统计列表
const demandStasticsListURL='demand/demandStasticsList';//数据统计模块-订单管理-需求单统计列表 
const demandRealPurchaseListURL='demand/demandRealPurchaseList';//数据统计模块-订单管理-需求单对应采购期的批次列表
const demandPurchaseGoodsDetailURL='demand/demandPurchaseGoodsDetail';//数据统计模块-订单管理-需求单对应采购期中的商品信息
const demandRealPurchaseDetailURL='demand/demandRealPurchaseDetail';//数据统计模块-订单管理-需求单对应采购期批次中的商品信息
const orderCurrentStatisticsListURL='demand/orderCurrentStatisticsList';//订单统计列表
const subOrderStatisticsListURL='demand/subOrderStatisticsList';//子单统计列表
const goodsStatisticsListURL='Statistics/goodsStatisticsList';//数据统计模块-订单管理-商品统计列表
const purchaseChannelStatisticsListURL='Statistics/purchaseChannelStatisticsList';//数据统计模块-采购期统计管理-采购期渠道统计列表
const purchaseChannelStatisticsDetailURL='Statistics/purchaseChannelStatisticsDetail';//数据统计模块-采购期统计管理-采购期渠道统计详情
const delPurchaseSumDateURL='Statistics/delPurchaseSumDate';//数据统计模式-删除合期数据
const currentGoodsStatisticsListURL='Statistics/currentGoodsStatisticsList';//数据统计模块-采购期统计管理-当月实采商品统计列表

//系统设置模块
const getMarginRateListURL='Goods/getMarginRateList';//系统设置-销售模块-自采毛利率列表
const delMarginRateURL='Goods/delMarginRate';//系统设置-销售模块-删除自采毛利率
const discountExportURL='Discount/discountExport';//导出采购折扣
const accountListURL='Finance/accountList';//渠道积分列表
const addChannelIntegralURL='Finance/addChannelIntegral';//新增渠道积分
const doAddChannelIntegralURL='Finance/doAddChannelIntegral';//提交新增渠道积分
const editChannelIntegralURL='Finance/editChannelIntegral';//编辑渠道积分
const doEditChannelIntegralURL='Finance/doEditChannelIntegral';//提交编辑渠道积分
const waitIntegralInfoURL='Finance/waitIntegralInfo';//待返积分详情
const importAdvanceURL='misOrder/importAdvance';//预判数据导入
const waitIntegralListURL='Finance/waitIntegralList';//待返积分批次列表
const waitIntegralDetailURL='Finance/waitIntegralDetail';//待返积分批次详情
const submitIntegralURL='Finance/submitIntegral';//确认提交积分
const discountTypeListURL='Discount/discountTypeList';//获取折扣类型列表
const addDiscountTypeURL='Discount/addDiscountType';//系统设置-采购模块-采购折扣列表-打开新增折扣类型页面
const doAddDiscountTypeURL='Discount/doAddDiscountType';//系统设置-采购模块-采购折扣列表-新增折扣类型
const doUploadDiscountTypeURL='Discount/doUploadDiscountType';//维护折扣类型对应的折扣
const discountTotalListURL='Discount/discountTotalList';//采购折扣列表
const accountDetailURL='Finance/accountDetail';//系统设置-财务模块-账户列表-折线图
const getGmcDiscountListURL='Discount/getGmcDiscountList';//获取商品特殊折扣列表
const uploadGmcDiscountURL='Discount/uploadGmcDiscount';//商品渠道追加折扣维护
const methodChannelsTypeListURL='Discount/methodChannelsTypeList';//打开维护折扣类型对应的折扣页面
const discountTypeSettingURL='Discount/discountTypeSetting';//折扣档位设置
const editDiscountTypeURL='Discount/editDiscountType';//编辑折扣档位
const discountTypeLogListURL='Discount/discountTypeLogList';//系统设置-采购模块-获取折扣类型记录列表
const doAddDiscountTypeLogURL='Discount/doAddDiscountTypeLog';//系统设置-采购模块-新增折扣类型记录
const downloadDiscountDiffGoodsURL='Discount/downloadDiscountDiffGoods';//系统设置-采购模块-新增折扣类型记录 
const makeGoodsOfferURL='Discount/makeGoodsOffer';//导出商品最终报价
const brandDiscountListURL='Demand/brandDiscountList';//品牌折扣列表
const getOfferFileURL='Discount/getOfferFile';//获取商品报价导出文件
const getShopCartListURL='Goods/getShopCartList';//获取购物车列表
const uploadShopCartGoodsURL='Goods/uploadShopCartGoods';//上传购物车商品
const downloadShopDiffGoodsURL='Goods/downloadShopDiffGoods';//上传购物车商品
const targetListURL='System/targetList';//上传购物车商品
const addTargetURL='System/addTarget';//新增目标
const editTargetURL='System/editTarget';//编辑目标
const getSaleUserListURL='System/getSaleUserList';//获取用户信息
const makeCartOfferURL='Discount/makeCartOffer';//生成购物车报价数据
const getCartOfferFileURL='Discount/getCartOfferFile';//获取购物车报价导出文件
const getGoodsSaleListURL='Goods/getGoodsSaleList';//获取商品报价列表
const uploadGoodsSaleInfoURL='Goods/uploadGoodsSaleInfo';//上传商品报价
const downloadSaleDiffGoodsURL='Goods/downloadSaleDiffGoods';//下载商品报价新品
const getBuyChannelURL='Discount/getBuyChannel';//获取采购渠道信息
const goodsAddMarginRateURL='Goods/addMarginRate';//系统设置-销售模块-新增自采毛利率

//日志模块
const getLoggerListURL='logger/getLoggerList';//获取日志列表
const getLoggerDetailURL='logger/getLoggerDetail';//获取日志详情
const getVersionListURL='logger/getVersionList';//获取版本日志记录列表
const addVersionLogURL='logger/addVersionLog';//新增版本日志记录
const editVersionLogURL='logger/editVersionLog';//编辑版本日志记录

//审核模块
const authListURL='purchase_discount/authList';//获取日志详情
const discountAuditDetailURL='purchase_discount/discountAuditDetail';//品牌折扣上传数据详情
const modifyBrandDiscountURL='purchase_discount/modifyBrandDiscount';//品牌折扣上传数据-修改
const auditBrandDiscountURL='purchase_discount/auditBrandDiscount';//品牌折扣上传数据-审核
const submitBrandDiscountURL='purchase_discount/submitBrandDiscount';//
const batchAuditDetailURL='Batch/batchAuditDetail';//采购模块-采购数据管理-获取待审核采购批次详情
const doBatchAuditURL='Batch/doBatchAudit';//采购模块-采购数据管理-提交批次审核
const uploadBatchAuditURL='Batch/uploadBatchAudit';//采购模块-采购数据管理-提交批次数据
const discountExportByGoodsURL='Discount/discountExportByGoods';//测试
const modifyBatchDataURL='Batch/modifyBatchData';//审核模块-批次审核列表-采购数据修正

//用户模块
const UserListURL='User/userList';//获取用户列表
const getUserClassifyURL='User/getUserClassify';//获取用户分类信息
const addUserURL='User/addUser';//新增用户
const getUserClassifyListURL='User/getUserClassifyList';//获取用户分类列表
const usereditUserURL='User/editUser';//编辑用户 
const getClassifyFieldURL='User/getClassifyField';//获取分类可见字段信息
const addClassifyURL='User/addClassify';//新增用户分类
const getClassifyShopURL='User/getClassifyShop';//获取分类店铺信息
const editClassifyURL='User/editClassify';//编辑用户分类



//登录后的token值
const headersToken=sessionStorage.getItem("token");
// const headersStr={'Authorization': 'Bearer ' + sessionStorage.getItem("token"),'Accept':'application/vnd.jmsapi.v1+json'};
// var headersStr='';
export default {
 install () {
    //文件路径
    Vue.prototype.$pathOfFileVue = pathOfFileVue;
    Vue.prototype.$pathOfFileCss = pathOfFileCss;
    Vue.prototype.$pathOfFileJS = pathOfFileJS;
    Vue.prototype.$pathOfFileImg = pathOfFileImg;


    //首页
    Vue.prototype.$purchaseTaskListURL = purchaseTaskListURL;
    Vue.prototype.$firstPageURL = firstPageURL;
    Vue.prototype.$sumDemandInfoURL = sumDemandInfoURL;
    Vue.prototype.$sumDiffInfoURL = sumDiffInfoURL;
    Vue.prototype.$ddGoodsRankListURL = ddGoodsRankListURL;
    Vue.prototype.$getSaleUserURL = getSaleUserURL;
    Vue.prototype.$uploadAdminUserImgURL = uploadAdminUserImgURL;
    //采购模块
    Vue.prototype.$getWaiteOrder = getWaiteOrder;
    Vue.prototype.$createDate=createDate;
    Vue.prototype.$passDateList=passDateList;
    Vue.prototype.$editDate=editDate;
    Vue.prototype.$doEditDate=doEditDate;
    Vue.prototype.$channelsListURL=channelsListURL;
    Vue.prototype.$createChannelsURL=createChannelsURL;
    Vue.prototype.$createMethodURL=createMethodURL;
    Vue.prototype.$discountListURL=discountListURL;
    Vue.prototype.$downloadDiscountDemoURL=downloadDiscountDemoURL;
    Vue.prototype.$downloadDiscountCurrentURL=downloadDiscountCurrentURL;
    Vue.prototype.$uploadDiscountURL=uploadDiscountURL;
    Vue.prototype.$methodListURL=methodListURL;
    Vue.prototype.$createCostURL=createCostURL;
    Vue.prototype.$costListURL=costListURL;
    Vue.prototype.$editCostURL=editCostURL;
    Vue.prototype.$demandListURL=demandListURL;
    Vue.prototype.$demandDetailURL=demandDetailURL;
    Vue.prototype.$changeGoodsURL=changeGoodsURL;
    Vue.prototype.$changeDemandStatusURL=changeDemandStatusURL;
    Vue.prototype.$downloadDemandListURL=downloadDemandListURL;
    Vue.prototype.$doEditMethodURL=doEditMethodURL;
    Vue.prototype.$editMethodURL=editMethodURL;
    Vue.prototype.$recommendListURL=recommendListURL;
    Vue.prototype.$recommendDetailURL=recommendDetailURL;
    Vue.prototype.$downloadRecommendListURL=downloadRecommendListURL;
    Vue.prototype.$uploadDataURL=uploadDataURL;
    Vue.prototype.$dataListURL=dataListURL;
    Vue.prototype.$userListURL=userListURL;
    Vue.prototype.$batchListURL=batchListURL;
    Vue.prototype.$batchDetailURL=batchDetailURL;
    Vue.prototype.$downloadBatchListURL=downloadBatchListURL;
    Vue.prototype.$diffListURL=diffListURL;
    Vue.prototype.$diffDetailURL=diffDetailURL;
    Vue.prototype.$changeDiffStatusURL=changeDiffStatusURL;
    Vue.prototype.$expireDiffListURL=expireDiffListURL;
    Vue.prototype.$billingListURL=billingListURL;
    Vue.prototype.$billingDetailURL=billingDetailURL;
    Vue.prototype.$changeBillingStatusURL=changeBillingStatusURL;
    Vue.prototype.$expireBillingListURL=expireBillingListURL;
    Vue.prototype.$createUserURL=createUserURL;
    Vue.prototype.$checkPurchaseDatePassURL=checkPurchaseDatePassURL;
    Vue.prototype.$addDiffRemarkURL=addDiffRemarkURL;
    Vue.prototype.$dataManagementListURL=dataManagementListURL;
    Vue.prototype.$dataGoodsListURL=dataGoodsListURL;
    Vue.prototype.$editUserURL=editUserURL;
    Vue.prototype.$doEditUserURL=doEditUserURL;
    Vue.prototype.$downloadDiffListURL=downloadDiffListURL;
    Vue.prototype.$downloadBillingListURL=downloadBillingListURL;
    Vue.prototype.$channelMethodListURL=channelMethodListURL;
    Vue.prototype.$uploadDiffDataURL=uploadDiffDataURL;
    Vue.prototype.$douploadDiffDataURL=douploadDiffDataURL;
    Vue.prototype.$doUploadDataURL=doUploadDataURL;
    Vue.prototype.$closePurchaseURL=closePurchaseURL;
    Vue.prototype.$modifyDataListURL=modifyDataListURL;
    Vue.prototype.$goodsStockOutListURL=goodsStockOutListURL;
    Vue.prototype.$purchaseListURL=purchaseListURL;
    Vue.prototype.$uploadDemandURL=uploadDemandURL;
    Vue.prototype.$purchaseOutListURL=purchaseOutListURL;
    Vue.prototype.$doUploadDemandURL=doUploadDemandURL;
    Vue.prototype.$waitAllotDemandURL=waitAllotDemandURL;
    Vue.prototype.$alreadyAllotDemandURL=alreadyAllotDemandURL;
    Vue.prototype.$demandAttachURL=demandAttachURL;
    Vue.prototype.$doDemandAttachURL=doDemandAttachURL;
    Vue.prototype.$demandAllotURL=demandAllotURL;
    Vue.prototype.$purchaseDemandAllotURL=purchaseDemandAllotURL;
    Vue.prototype.$editDemandAllotURL=editDemandAllotURL;
    Vue.prototype.$doEditDemandAllotURL=doEditDemandAllotURL;
    Vue.prototype.$demandDetailTURL=demandDetailTURL;
    Vue.prototype.$demandAlreadyDetailURL=demandAlreadyDetailURL;
    Vue.prototype.$purchaseDemandAlreadyURL=purchaseDemandAlreadyURL;
    Vue.prototype.$doDemandAllotURL=doDemandAllotURL;
    Vue.prototype.$departSortGoodsURL=departSortGoodsURL;
    Vue.prototype.$getDemandDetialURL=getDemandDetialURL;
    Vue.prototype.$predictDemandListURL=predictDemandListURL;
    Vue.prototype.$downloadPredictDemandtURL=downloadPredictDemandtURL;
    Vue.prototype.$uploadPredictRealURL=uploadPredictRealURL;
    Vue.prototype.$doUploadPredictRealURL=doUploadPredictRealURL;
    Vue.prototype.$predictDetailURL=predictDetailURL;
    Vue.prototype.$vipDiscountListURL=vipDiscountListURL;
    Vue.prototype.$doBatchSettingPostURL=doBatchSettingPostURL;
    Vue.prototype.$supplierListURL=supplierListURL;
    Vue.prototype.$addSupplierURL=addSupplierURL;
    Vue.prototype.$editChannelURL=editChannelURL;
    Vue.prototype.$doEditChannelURL=doEditChannelURL;
    Vue.prototype.$addBrandDiscountURL=addBrandDiscountURL;
    Vue.prototype.$doAddBrandDiscountURL=doAddBrandDiscountURL;
    Vue.prototype.$downLoadWaitAllotGoodsInfoURL=downLoadWaitAllotGoodsInfoURL;
    Vue.prototype.$uploadWaitAllotGoodsInfoURL=uploadWaitAllotGoodsInfoURL;
    Vue.prototype.$batchAddBrandDiscountURL=batchAddBrandDiscountURL;
    Vue.prototype.$batchAuditListURL=batchAuditListURL;
    Vue.prototype.$purchaseDemandListURL=purchaseDemandListURL;
    Vue.prototype.$sumPurchaseDemandURL=sumPurchaseDemandURL;
    Vue.prototype.$demandPurchaseTaskListURL=demandPurchaseTaskListURL;
    Vue.prototype.$downLoadSumDemandGoodsInfoURL=downLoadSumDemandGoodsInfoURL;
    Vue.prototype.$purchaseTaskDetailURL=purchaseTaskDetailURL;
    Vue.prototype.$uploadBatchDataURL=uploadBatchDataURL;
    Vue.prototype.$uploadSumDemandGoodsInfoURL=uploadSumDemandGoodsInfoURL;
    Vue.prototype.$getMisOrderSplitURL=getMisOrderSplitURL;
    Vue.prototype.$modifyDDSubDataURL=modifyDDSubDataURL;
    Vue.prototype.$BatchUploadBatchDataURL=BatchUploadBatchDataURL;
    Vue.prototype.$doUploadBatchDataURL=doUploadBatchDataURL;
    Vue.prototype.$purchaseDemandDetailURL=purchaseDemandDetailURL;
    Vue.prototype.$addSumDemandURL=addSumDemandURL;
    Vue.prototype.$doAddSumDemandURL=doAddSumDemandURL;
    Vue.prototype.$downLoadSdgInfoNoSortURL=downLoadSdgInfoNoSortURL;
    Vue.prototype.$splitSumDemandURL=splitSumDemandURL;
    Vue.prototype.$getCardConsumeListURL=getCardConsumeListURL;
    Vue.prototype.$addCardConsumeURL=addCardConsumeURL;
    Vue.prototype.$doAddCardConsumeURL=doAddCardConsumeURL;
    Vue.prototype.$teamListURL=teamListURL;
    Vue.prototype.$addTeamURL=addTeamURL;
    Vue.prototype.$editTeamURL=editTeamURL;


    //销售模块
    Vue.prototype.$managerURL=managerURL;
    Vue.prototype.$demGoodsUpURL=demGoodsUpURL;
    Vue.prototype.$getPageDataURL=getPageDataURL;
    Vue.prototype.$getCompletePurListURL=getCompletePurListURL;
    Vue.prototype.$getGoodsAllotListURL=getGoodsAllotListURL;
    Vue.prototype.$getGoodsAllotURL=getGoodsAllotURL;
    Vue.prototype.$goodsRealAllotURL=goodsRealAllotURL;
    Vue.prototype.$getGoodsActAllotListURL=getGoodsActAllotListURL;
    Vue.prototype.$goodsRtMovePercentURL=goodsRtMovePercentURL;
    Vue.prototype.$sellWaitOrderURL=sellWaitOrderURL;
    Vue.prototype.$sellOutOrderURL=sellOutOrderURL;
    Vue.prototype.$sellCusOrderURL=sellCusOrderURL;
    Vue.prototype.$sellOutCusOrderURL=sellOutCusOrderURL;
    Vue.prototype.$getGoodsAllotRealURL=getGoodsAllotRealURL;
    Vue.prototype.$getGoodsAllotTwoURL=getGoodsAllotTwoURL;
    Vue.prototype.$goodsStockListURL=goodsStockListURL;
    Vue.prototype.$queryDemDetailURL=queryDemDetailURL;
    Vue.prototype.$getRealPurListURL=getRealPurListURL;
    Vue.prototype.$getRealGoodsInfoURL=getRealGoodsInfoURL;
    Vue.prototype.$updateRealAllotNumURL=updateRealAllotNumURL;
    Vue.prototype.$getPurOrderListURL=getPurOrderListURL;
    Vue.prototype.$getPurDemOrdListURL=getPurDemOrdListURL;
    Vue.prototype.$getPurDemOrdInfoURL=getPurDemOrdInfoURL;
    Vue.prototype.$getNeedGoodsListURL=getNeedGoodsListURL;
    Vue.prototype.$demandAllotListURL=demandAllotListURL;
    Vue.prototype.$demandPurchaseListURL=demandPurchaseListURL;
    Vue.prototype.$demandPurchaseDetailURL=demandPurchaseDetailURL;
    Vue.prototype.$newDemPageURL=newDemPageURL;
    Vue.prototype.$updateSaleRateURL=updateSaleRateURL;
    Vue.prototype.$getChannelByMethodURL=getChannelByMethodURL;
    Vue.prototype.$depHandleGoodsURL=depHandleGoodsURL;
    Vue.prototype.$userSortGoodsURL=userSortGoodsURL;
    Vue.prototype.$usrHandleGoodsURL=usrHandleGoodsURL;
    Vue.prototype.$purRealListURL=purRealListURL;
    Vue.prototype.$demandAllotDetailURL=demandAllotDetailURL;
    Vue.prototype.$demandPassageListURL=demandPassageListURL;
    Vue.prototype.$passageRealPurchaseListURL=passageRealPurchaseListURL;
    Vue.prototype.$passageRealPurchaseDetailURL=passageRealPurchaseDetailURL;
    Vue.prototype.$saleAccountListURL=saleAccountListURL;
    Vue.prototype.$addSaleAccountURL=addSaleAccountURL;
    Vue.prototype.$doAddSaleAccountURL=doAddSaleAccountURL;
    Vue.prototype.$editSaleAccountURL=editSaleAccountURL;
    Vue.prototype.$doEditSaleAccounttURL=doEditSaleAccounttURL;
    Vue.prototype.$getMisOrderListURL=getMisOrderListURL;
    Vue.prototype.$getMisOrderDetailURL=getMisOrderDetailURL;
    Vue.prototype.$refundRulesListURL=refundRulesListURL;
    Vue.prototype.$addRefundRulesURL=addRefundRulesURL;
    Vue.prototype.$doAddRefundRulesURL=doAddRefundRulesURL;
    Vue.prototype.$editRefundRulesURL=editRefundRulesURL;
    Vue.prototype.$doEditRefundRulesURL=doEditRefundRulesURL;
    Vue.prototype.$misSubOrderListURL=misSubOrderListURL;
    Vue.prototype.$misCanDeliverGoodsURL=misCanDeliverGoodsURL;
    Vue.prototype.$comfirmDeliverGoodsURL=comfirmDeliverGoodsURL;
    Vue.prototype.$getSubListURL=getSubListURL;getSubDetailURL
    Vue.prototype.$getSubDetailURL=getSubDetailURL;
    Vue.prototype.$getSpotListURL=getSpotListURL;
    Vue.prototype.$getSpotDetailURL=getSpotDetailURL;
    Vue.prototype.$importOrderPageURL=importOrderPageURL;
    Vue.prototype.$importOrderURL=importOrderURL;
    Vue.prototype.$ordGoodsOfferURL=ordGoodsOfferURL;
    Vue.prototype.$orderAffiliateURL=orderAffiliateURL;
    Vue.prototype.$cancelSpotOrdURL=cancelSpotOrdURL;
    Vue.prototype.$erpOrderPushURL=erpOrderPushURL;
    Vue.prototype.$exportSubOrdURL=exportSubOrdURL;
    Vue.prototype.$importSubOrdURL=importSubOrdURL;
    Vue.prototype.$listSaleAccountURL=listSaleAccountURL;
    Vue.prototype.$orderSubmenuURL=orderSubmenuURL;
    Vue.prototype.$subOrdSubmenuURL=subOrdSubmenuURL;
    Vue.prototype.$modSaleDiscountURL=modSaleDiscountURL;
    Vue.prototype.$demandGoodsMarkURL=demandGoodsMarkURL;
    Vue.prototype.$sellDeliverOrderListURL=sellDeliverOrderListURL;
    Vue.prototype.$downloadSellDeliverOrderURL=downloadSellDeliverOrderURL;
    Vue.prototype.$doUploadSellDeliverOrderURL=doUploadSellDeliverOrderURL;
    Vue.prototype.$sellReturnOrderDetailURL=sellReturnOrderDetailURL;
    Vue.prototype.$misOrderExportURL=misOrderExportURL;
    Vue.prototype.$finishOfferURL=finishOfferURL;
    Vue.prototype.$batchModSaleDiscountURL=batchModSaleDiscountURL;
    Vue.prototype.$modifyWaitLockNumURL=modifyWaitLockNumURL;
    Vue.prototype.$modifyRemarkURL=modifyRemarkURL;
    Vue.prototype.$editArriveStoreTimeURL=editArriveStoreTimeURL;
    Vue.prototype.$generalDepartSortDataURL=generalDepartSortDataURL;
    Vue.prototype.$getSortDataURL=getSortDataURL;
    Vue.prototype.$generalUserSortDataURL=generalUserSortDataURL;
    Vue.prototype.$getUserSortDataURL=getUserSortDataURL;
    Vue.prototype.$userHandleGoodsURL=userHandleGoodsURL;
    Vue.prototype.$modSaleDiscountBySpecURL=modSaleDiscountBySpecURL;
    Vue.prototype.$finishAdvanceURL=finishAdvanceURL;
    Vue.prototype.$stopDepartSortDataURL=stopDepartSortDataURL;
    Vue.prototype.$makePerDepartSortDataURL=makePerDepartSortDataURL;
    Vue.prototype.$finishAffiliatedURL=finishAffiliatedURL;
    Vue.prototype.$batchAffiliateURL=batchAffiliateURL;
    Vue.prototype.$getOrderNewGoodsURL=getOrderNewGoodsURL;
    Vue.prototype.$queryNewGoodsDataURL=queryNewGoodsDataURL;
    Vue.prototype.$modifyNewGoodsDataURL=modifyNewGoodsDataURL;
    Vue.prototype.$addNewGoodsDataURL=addNewGoodsDataURL;
    Vue.prototype.$batchAddNewGoodsURL=batchAddNewGoodsURL;
    Vue.prototype.$replenishGoodsIntoOrderURL=replenishGoodsIntoOrderURL;
    Vue.prototype.$addSpecPageURL=addSpecPageURL;
    Vue.prototype.$searchGoodsNameURL=searchGoodsNameURL;
    Vue.prototype.$addSpecDataURL=addSpecDataURL;
    Vue.prototype.$exportAdvanceURL=exportAdvanceURL;
    Vue.prototype.$submitSubOrdURL=submitSubOrdURL;
    Vue.prototype.$markGoodsPostponeURL=markGoodsPostponeURL;
    Vue.prototype.$importDDSubOrdURL=importDDSubOrdURL;
    Vue.prototype.$submitDDataURL=submitDDataURL;
    Vue.prototype.$batchOrderListURL=batchOrderListURL;
    Vue.prototype.$generalSortDataURL=generalSortDataURL;
    Vue.prototype.$sumSortDataListURL=sumSortDataListURL;
    Vue.prototype.$batchOrdSortDataURL=batchOrdSortDataURL;
    Vue.prototype.$handleSortNumURL=handleSortNumURL;
    Vue.prototype.$makeBatchOrdSortDataURL=makeBatchOrdSortDataURL;
    Vue.prototype.$exportOrdNewURL=exportOrdNewURL;
    Vue.prototype.$importOrdNewURL=importOrdNewURL;
    Vue.prototype.$exportOfferURL=exportOfferURL;
    Vue.prototype.$importOfferURL=importOfferURL;
    Vue.prototype.$downLoadDailyInfoURL=downLoadDailyInfoURL;
    Vue.prototype.$getGoodsNewPriceURL=getGoodsNewPriceURL;
    Vue.prototype.$modifyNewPriceURL=modifyNewPriceURL;
    Vue.prototype.$submitNewPriceURL=submitNewPriceURL;
    Vue.prototype.$downLoadTodayPurTaskURL=downLoadTodayPurTaskURL;
    Vue.prototype.$demandDemandListURL=demandDemandListURL;

    //物流模块 
    Vue.prototype.$goodsCheckListURL=goodsCheckListURL;
    Vue.prototype.$allotGoodsURL=allotGoodsURL;
    Vue.prototype.$allotStockGoodsURL=allotStockGoodsURL;
    Vue.prototype.$allotGoodsNumURL=allotGoodsNumURL;
    Vue.prototype.$sureAllotURL=sureAllotURL;
    Vue.prototype.$downloadAllotGoodsURL=downloadAllotGoodsURL;
    Vue.prototype.$getCusTransitOrderURL=getCusTransitOrderURL;
    Vue.prototype.$inputStorageURL=inputStorageURL;
    Vue.prototype.$LigWaitOrderURL=LigWaitOrderURL;
    Vue.prototype.$ligCusOrderURL=ligCusOrderURL;
    Vue.prototype.$ligCusOrderURL=ligCusOrderURL;
    Vue.prototype.$ligOutCusOrderURL=ligOutCusOrderURL;
    Vue.prototype.$goodsCheckOutListURL=goodsCheckOutListURL;
    Vue.prototype.$ligOutOrderURL=ligOutOrderURL;
    Vue.prototype.$uploadWaitCusOrdURL=uploadWaitCusOrdURL;
    Vue.prototype.$uploadCusTransitOrdURL=uploadCusTransitOrdURL;
    Vue.prototype.$uploadAllotDataURL=uploadAllotDataURL;
    Vue.prototype.$getOutCusTransitOrderURL=getOutCusTransitOrderURL;
    Vue.prototype.$upDeliverOrdURL=upDeliverOrdURL;
    Vue.prototype.$distributionOrderListURL=distributionOrderListURL;
    Vue.prototype.$distributionOrderDetailURL=distributionOrderDetailURL;
    Vue.prototype.$downloadDistributionOrderURL=downloadDistributionOrderURL;
    Vue.prototype.$doUploadDistributionOrderURL=doUploadDistributionOrderURL;
    Vue.prototype.$sellReturnOrderListURL=sellReturnOrderListURL;
    Vue.prototype.$downloadSellReturnGoodsURL=downloadSellReturnGoodsURL;
    Vue.prototype.$doUploadSellReturnGoodsURL=doUploadSellReturnGoodsURL;

    //权限模块
    Vue.prototype.$getPermissionURL=getPermissionURL;
    Vue.prototype.$addPermissionURL=addPermissionURL;
    Vue.prototype.$permissiomListURL=permissiomListURL;
    Vue.prototype.$addRoleURL=addRoleURL;
    Vue.prototype.$roleListURL=roleListURL;
    Vue.prototype.$editRoleURL=editRoleURL;
    Vue.prototype.$addAdminUserURL=addAdminUserURL;
    Vue.prototype.$adminUserListURL=adminUserListURL;
    Vue.prototype.$eidtAdminUserURL=eidtAdminUserURL;
    Vue.prototype.$getAdminUserInfoURL=getAdminUserInfoURL;

    //查看汇总详情
    Vue.prototype.$recommendTotalDetailURL=recommendTotalDetailURL;
    Vue.prototype.$downloadRecommendTotalListURL=downloadRecommendTotalListURL;
    Vue.prototype.$demandTotalDetailURL=demandTotalDetailURL;
    Vue.prototype.$downloadDemandTotalListURL=downloadDemandTotalListURL;
    Vue.prototype.$dataTotalDetailURL=dataTotalDetailURL;
    Vue.prototype.$downloadDataTotalListURL=downloadDataTotalListURL;
    Vue.prototype.$batchTotalDetailURL=batchTotalDetailURL;
    Vue.prototype.$downloadBatchTotalListURL=downloadBatchTotalListURL;
    Vue.prototype.$diffTotalDetailURL=diffTotalDetailURL;
    Vue.prototype.$downloadDiffTotalListURL=downloadDiffTotalListURL;
    Vue.prototype.$billingTotalDetailURL=billingTotalDetailURL;
    Vue.prototype.$downloadBillingTotalListURL=downloadBillingTotalListURL;

    //任务模块
    Vue.prototype.$taskListURL=taskListURL;
    Vue.prototype.$addTaskDetailURL=addTaskDetailURL;
    Vue.prototype.$addTaskURL=addTaskURL;
    Vue.prototype.$userOfRoleURL=userOfRoleURL;
    Vue.prototype.$getPurchaseTaskURL=getPurchaseTaskURL;
    Vue.prototype.$changeTaskStatusURL=changeTaskStatusURL;
    Vue.prototype.$batchSettingURL=batchSettingURL;
    Vue.prototype.$doBatchSettingURL=doBatchSettingURL;
    Vue.prototype.$taskModelListURL=taskModelListURL;
    Vue.prototype.$checkTaskModelURL=checkTaskModelURL;
    Vue.prototype.$editTaskURL=editTaskURL;
    Vue.prototype.$doEditTaskURL=doEditTaskURL;

    //商品模块
    Vue.prototype.$goodsListURL=goodsListURL;
    Vue.prototype.$changeSaleStatusURL=changeSaleStatusURL;
    Vue.prototype.$doAddGoodsURL=doAddGoodsURL;
    Vue.prototype.$addGoodsURL=addGoodsURL;
    Vue.prototype.$uploadGoodsImgURL=uploadGoodsImgURL;
    Vue.prototype.$uploadAddGoodsURL=uploadAddGoodsURL;
    Vue.prototype.$editGoodsURL=editGoodsURL;
    Vue.prototype.$doEditGoodsURL=doEditGoodsURL;
    Vue.prototype.$saleUserListURL=saleUserListURL;
    Vue.prototype.$userGoodsListURL=userGoodsListURL;
    Vue.prototype.$upSaleGoodsURL=upSaleGoodsURL;
    Vue.prototype.$modSaleRateURL=modSaleRateURL;
    Vue.prototype.$batchSaleDisURL=batchSaleDisURL;
    Vue.prototype.$addCustomerURL=addCustomerURL;
    Vue.prototype.$doAddCustomerURL=doAddCustomerURL;
    Vue.prototype.$goodsSpecListURL=goodsSpecListURL;
    Vue.prototype.$doAddGoodsSpecURL=doAddGoodsSpecURL;
    Vue.prototype.$editGoodsSpecURL=editGoodsSpecURL;
    Vue.prototype.$doEditGoodsSpecURL=doEditGoodsSpecURL;
    Vue.prototype.$editCustomerURL=editCustomerURL;
    Vue.prototype.$doEditCustomerURL=doEditCustomerURL;
    Vue.prototype.$getErpGoodsListURL=getErpGoodsListURL;
    Vue.prototype.$addGoodsCodeURL=addGoodsCodeURL;
    Vue.prototype.$doAddGoodsCodeURL=doAddGoodsCodeURL;
    Vue.prototype.$editGoodsCodeURL=editGoodsCodeURL;
    Vue.prototype.$goodsLabelListURL=goodsLabelListURL;
    Vue.prototype.$doAddGoodsLabelURL=doAddGoodsLabelURL;
    Vue.prototype.$editGoodsLabelURL=editGoodsLabelURL;
    Vue.prototype.$doEditGoodsLabelURL=doEditGoodsLabelURL;
    Vue.prototype.$doEditGoodsCodeURL=doEditGoodsCodeURL;
    Vue.prototype.$addGoodsSpecURL=addGoodsSpecURL;
    Vue.prototype.$standbyGoodsListURL=standbyGoodsListURL;
    Vue.prototype.$standbyGoodsInfoURL=standbyGoodsInfoURL;
    Vue.prototype.$doEditStandbyGoodsURL=doEditStandbyGoodsURL;
    Vue.prototype.$uploadStandbyGoodsDataURL=uploadStandbyGoodsDataURL;
    Vue.prototype.$downLoadStandbyGoodsInfoURL=downLoadStandbyGoodsInfoURL;
    Vue.prototype.$addStandbyGoodsURL=addStandbyGoodsURL;
    Vue.prototype.$uploadStandbyGoodsURL=uploadStandbyGoodsURL;
    Vue.prototype.$offerListURL=offerListURL;
    Vue.prototype.$getOfferDetailURL=getOfferDetailURL;
    Vue.prototype.$offerSkuUploadURL=offerSkuUploadURL;
    Vue.prototype.$modifySkuDiscountURL=modifySkuDiscountURL;
    Vue.prototype.$exportSkuOfferURL=exportSkuOfferURL;
    Vue.prototype.$importSkuOfferURL=importSkuOfferURL;
    Vue.prototype.$goodsDetailURL=goodsDetailURL;
    Vue.prototype.$ltGoodsListURL=ltGoodsListURL;
    Vue.prototype.$ltGoodsSpecPriceInfoURL=ltGoodsSpecPriceInfoURL;
    Vue.prototype.$wholesaleListURL=wholesaleListURL;
    Vue.prototype.$getWholesaleDetailURL=getWholesaleDetailURL;
    Vue.prototype.$importWholesaleSkuURL=importWholesaleSkuURL;
    Vue.prototype.$exportWholesaleOfferURL=exportWholesaleOfferURL;
    Vue.prototype.$getWholeDetailURL=getWholeDetailURL;
    Vue.prototype.$wholesaleExportURL=wholesaleExportURL;
    Vue.prototype.$modifyWholeDataURL=modifyWholeDataURL;
    Vue.prototype.$batchModifyWholeDataURL=batchModifyWholeDataURL;

    //公告模块
    Vue.prototype.$addNoticeURL=addNoticeURL;
    Vue.prototype.$noticeListURL=noticeListURL;

    //报价器
    Vue.prototype.$queryNeedGoodsInfoURL=queryNeedGoodsInfoURL;
    Vue.prototype.$addMarginRateURL=addMarginRateURL;
    Vue.prototype.$modifyPricingRateURL=modifyPricingRateURL;
    Vue.prototype.$batchModPricRateURL=batchModPricRateURL;
    Vue.prototype.$getChargeListURL=getChargeListURL;
    Vue.prototype.$addChargeURL=addChargeURL;
    Vue.prototype.$modifyChargeURL=modifyChargeURL;
    
    //订单管理
    Vue.prototype.$getOrderListURL=getOrderListURL;
    Vue.prototype.$orderDetailURL=orderDetailURL;

    //财务模块
    Vue.prototype.$getFundChannelListURL=getFundChannelListURL;
    Vue.prototype.$doAddFundChannelURL=doAddFundChannelURL;
    Vue.prototype.$addFundChannelURL=addFundChannelURL;
    Vue.prototype.$editFundChannelURL=editFundChannelURL;
    Vue.prototype.$doEditFundChannelURL=doEditFundChannelURL;
    Vue.prototype.$rongFundListURL=rongFundListURL;
    Vue.prototype.$editRongFundURL=editRongFundURL;
    Vue.prototype.$doEditRongFundURL=doEditRongFundURL;
    Vue.prototype.$discretionaryFundListURL=discretionaryFundListURL;
    Vue.prototype.$editDiscretionaryFundURL=editDiscretionaryFundURL;
    Vue.prototype.$doEditDiscretionaryFundURL=doEditDiscretionaryFundURL;
    Vue.prototype.$waitRefundListURL=waitRefundListURL;
    Vue.prototype.$demandFundListURL=demandFundListURL;
    Vue.prototype.$financeDeliverOrderListURL=financeDeliverOrderListURL;
    Vue.prototype.$financeChangeOrderStatusURL=financeChangeOrderStatusURL;
    Vue.prototype.$watiPricingBatchListURL=watiPricingBatchListURL;
    Vue.prototype.$watiPricingBatchDetailURL=watiPricingBatchDetailURL;
    Vue.prototype.$downloadPricingBatchDetailURL=downloadPricingBatchDetailURL;
    Vue.prototype.$doUploadPricingBatchURL=doUploadPricingBatchURL;
    Vue.prototype.$changePriceStatusURL=changePriceStatusURL;
    Vue.prototype.$fundListDetailURL=fundListDetailURL;
    Vue.prototype.$doPricingBatchURL=doPricingBatchURL;
    Vue.prototype.$demandGoodsFundListURL=demandGoodsFundListURL;
    Vue.prototype.$waitRefundDemandListURL=waitRefundDemandListURL;
    Vue.prototype.$waitRefundDemandDetailURL=waitRefundDemandDetailURL;
    Vue.prototype.$exchangeRateListURL=exchangeRateListURL;
    Vue.prototype.$uploadExchangeRateURL=uploadExchangeRateURL;
    Vue.prototype.$getProfitFormulaListURL=getProfitFormulaListURL;
    Vue.prototype.$getDiscountCatListURL=getDiscountCatListURL;
    Vue.prototype.$doAddProfitFormulaURL=doAddProfitFormulaURL;
    Vue.prototype.$profitListURL=profitListURL;
    Vue.prototype.$discountTypeListFinanceURL=discountTypeListFinanceURL;
    Vue.prototype.$generateProfitURL=generateProfitURL;
    Vue.prototype.$profitDetailURL=profitDetailURL;
    Vue.prototype.$downLoadProfitInfoURL=downLoadProfitInfoURL;
    Vue.prototype.$deleteProfitInfoURL=deleteProfitInfoURL;
    Vue.prototype.$doAddDiscountCatURL=doAddDiscountCatURL;
    Vue.prototype.$getCatFormulaListURL=getCatFormulaListURL;
    Vue.prototype.$addCatFormulaURL=addCatFormulaURL;
    Vue.prototype.$doAddCatFormulaURL=doAddCatFormulaURL;


    //数据汇总模块
    Vue.prototype.$misDemandListURL=misDemandListURL;
    Vue.prototype.$demandStasticsListURL=demandStasticsListURL;
    Vue.prototype.$demandRealPurchaseListURL=demandRealPurchaseListURL;
    Vue.prototype.$demandPurchaseGoodsDetailURL=demandPurchaseGoodsDetailURL;
    Vue.prototype.$demandRealPurchaseDetailURL=demandRealPurchaseDetailURL;
    Vue.prototype.$orderCurrentStatisticsListURL=orderCurrentStatisticsListURL;
    Vue.prototype.$subOrderStatisticsListURL=subOrderStatisticsListURL;
    Vue.prototype.$goodsStatisticsListURL=goodsStatisticsListURL;
    Vue.prototype.$purchaseChannelStatisticsListURL=purchaseChannelStatisticsListURL;
    Vue.prototype.$purchaseChannelStatisticsDetailURL=purchaseChannelStatisticsDetailURL;
    Vue.prototype.$delPurchaseSumDateURL=delPurchaseSumDateURL;
    Vue.prototype.$currentGoodsStatisticsListURL=currentGoodsStatisticsListURL;

    //系统设置模块
    Vue.prototype.$getMarginRateListURL=getMarginRateListURL;
    Vue.prototype.$delMarginRateURL=delMarginRateURL;
    Vue.prototype.$discountExportURL=discountExportURL;
    Vue.prototype.$accountListURL=accountListURL;
    Vue.prototype.$addChannelIntegralURL=addChannelIntegralURL;
    Vue.prototype.$doAddChannelIntegralURL=doAddChannelIntegralURL;
    Vue.prototype.$editChannelIntegralURL=editChannelIntegralURL;
    Vue.prototype.$doEditChannelIntegralURL=doEditChannelIntegralURL;
    Vue.prototype.$waitIntegralInfoURL=waitIntegralInfoURL;
    Vue.prototype.$importAdvanceURL=importAdvanceURL;
    Vue.prototype.$waitIntegralListURL=waitIntegralListURL;
    Vue.prototype.$waitIntegralDetailURL=waitIntegralDetailURL;
    Vue.prototype.$submitIntegralURL=submitIntegralURL;
    Vue.prototype.$discountTypeListURL=discountTypeListURL;
    Vue.prototype.$addDiscountTypeURL=addDiscountTypeURL;
    Vue.prototype.$doAddDiscountTypeURL=doAddDiscountTypeURL;
    Vue.prototype.$doUploadDiscountTypeURL=doUploadDiscountTypeURL;
    Vue.prototype.$discountTotalListURL=discountTotalListURL;
    Vue.prototype.$accountDetailURL=accountDetailURL;
    Vue.prototype.$getGmcDiscountListURL=getGmcDiscountListURL;
    Vue.prototype.$uploadGmcDiscountURL=uploadGmcDiscountURL;
    Vue.prototype.$methodChannelsTypeListURL=methodChannelsTypeListURL;
    Vue.prototype.$discountTypeSettingURL=discountTypeSettingURL;
    Vue.prototype.$editDiscountTypeURL=editDiscountTypeURL;
    Vue.prototype.$discountTypeLogListURL=discountTypeLogListURL;
    Vue.prototype.$doAddDiscountTypeLogURL=doAddDiscountTypeLogURL;
    Vue.prototype.$downloadDiscountDiffGoodsURL=downloadDiscountDiffGoodsURL;
    Vue.prototype.$makeGoodsOfferURL=makeGoodsOfferURL;
    Vue.prototype.$brandDiscountListURL=brandDiscountListURL;
    Vue.prototype.$getOfferFileURL=getOfferFileURL;
    Vue.prototype.$getShopCartListURL=getShopCartListURL;
    Vue.prototype.$uploadShopCartGoodsURL=uploadShopCartGoodsURL;
    Vue.prototype.$downloadShopDiffGoodsURL=downloadShopDiffGoodsURL;
    Vue.prototype.$targetListURL=targetListURL;
    Vue.prototype.$addTargetURL=addTargetURL;
    Vue.prototype.$editTargetURL=editTargetURL;
    Vue.prototype.$getSaleUserListURL=getSaleUserListURL;
    Vue.prototype.$makeCartOfferURL=makeCartOfferURL;
    Vue.prototype.$getCartOfferFileURL=getCartOfferFileURL;
    Vue.prototype.$getGoodsSaleListURL=getGoodsSaleListURL;
    Vue.prototype.$uploadGoodsSaleInfoURL=uploadGoodsSaleInfoURL;
    Vue.prototype.$downloadSaleDiffGoodsURL=downloadSaleDiffGoodsURL;
    Vue.prototype.$getBuyChannelURL=getBuyChannelURL;
    Vue.prototype.$goodsAddMarginRateURL=goodsAddMarginRateURL;

    //日志模块
    Vue.prototype.$getLoggerListURL=getLoggerListURL;
    Vue.prototype.$getLoggerDetailURL=getLoggerDetailURL;
    Vue.prototype.$getVersionListURL=getVersionListURL;
    Vue.prototype.$addVersionLogURL=addVersionLogURL;
    Vue.prototype.$editVersionLogURL=editVersionLogURL;

    //审核模块
    Vue.prototype.$authListURL=authListURL;
    Vue.prototype.$discountAuditDetailURL=discountAuditDetailURL;
    Vue.prototype.$modifyBrandDiscountURL=modifyBrandDiscountURL;
    Vue.prototype.$auditBrandDiscountURL=auditBrandDiscountURL;
    Vue.prototype.$submitBrandDiscountURL=submitBrandDiscountURL;
    Vue.prototype.$batchAuditDetailURL=batchAuditDetailURL;
    Vue.prototype.$doBatchAuditURL=doBatchAuditURL;
    Vue.prototype.$uploadBatchAuditURL=uploadBatchAuditURL;
    Vue.prototype.$discountExportByGoodsURL=discountExportByGoodsURL;
    Vue.prototype.$modifyBatchDataURL=modifyBatchDataURL;

    //用户模块
    Vue.prototype.$UserListURL=UserListURL;
    Vue.prototype.$getUserClassifyURL=getUserClassifyURL;
    Vue.prototype.$addUserURL=addUserURL;
    Vue.prototype.$getUserClassifyListURL=getUserClassifyListURL;
    Vue.prototype.$usereditUserURL=usereditUserURL;
    Vue.prototype.$getClassifyFieldURL=getClassifyFieldURL;
    Vue.prototype.$addClassifyURL=addClassifyURL;
    Vue.prototype.$getClassifyShopURL=getClassifyShopURL;
    Vue.prototype.$editClassifyURL=editClassifyURL;
 }
}



        